/*
 * Narukami TO - a server software reimplementation for a certain browser tank game.
 * Copyright (c) 2025  Daniil Pryima
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Affero General Public License for more details.
 *
 * You should have received a copy of the GNU Affero General Public License
 * along with this program.  If not, see <https://www.gnu.org/licenses/>.
 */

package jp.assasans.narukami.server.garage.item

import jp.assasans.narukami.server.protocol.IProtocolEnum
import jp.assasans.narukami.server.protocol.ProtocolEnum

@ProtocolEnum
enum class ItemGarageProperty(override val value: Int) : IProtocolEnum<Int> {
  HULL_ARMOR(0),
  HULL_SPEED(1),
  HULL_TURN_SPEED(2),
  HULL_POWER(3),
  HULL_MASS(4),
  ALL_RESISTANCE(5),
  FIREBIRD_RESISTANCE(6),
  SMOKY_RESISTANCE(7),
  TWINS_RESISTANCE(8),
  RAILGUN_RESISTANCE(9),
  ISIS_RESISTANCE(10),
  MINE_RESISTANCE(11),
  THUNDER_RESISTANCE(12),
  FREEZE_RESISTANCE(13),
  RICOCHET_RESISTANCE(14),
  SHAFT_RESISTANCE(15),
  SHOTGUN_RESISTANCE(16),
  MACHINE_GUN_RESISTANCE(17),
  ROCKET_LAUNCHER_RESISTANCE(18),
  ARTILLERY_RESISTANCE(19),
  GAUSS_RESISTANCE(20),
  DAMAGE(21),
  DAMAGE_PER_SECOND(22),
  WEAPON_COOLDOWN_TIME(23),
  AIMING_MODE_COOLDOWN_TIME(24),
  CRITICAL_HIT_CHANCE(25),
  CRITICAL_HIT_DAMAGE(26),
  SHOT_RANGE(27),
  TURRET_TURN_SPEED(28),
  AIMING_ERROR(29),
  SHOT_AREA(30),
  CONE_ANGLE(31),
  CHARGING_TIME(32),
  FIRE_DAMAGE(33),
  WEAPON_WEAKENING_COEFF(34),
  ISIS_DAMAGE(35),
  ISIS_HEALING_PER_SECOND(36),
  AIMING_MODE_DAMAGE(37),
  AIMING_WEAPON_DISCHARGE_RATE(38),
  SHAFT_AIMED_SHOT_IMPACT(39),
  SHAFT_TARGETING_SPEED(40),
  SHAFT_ARCADE_DAMAGE(41),
  GAUSS_AIMING_MODE_DAMAGE(42),
  WEAPON_IMPACT_FORCE(43),
  WEAPON_KICKBACK(44),
  SHELL_SPEED(45),
  WEAPON_CHARGE_RATE(46),
  WEAPON_MIN_DAMAGE_PERCENT(47),
  THUNDER_MIN_SPLASH_DAMAGE_PERCENT(48),
  DEPENDENCY_FIRST_AID_SEC(49),
  DEPENDENCY_DOUBLE_ARMOR_SEC(50),
  DEPENDENCY_DOUBLE_DAMAGE_SEC(51),
  DEPENDENCY_NITRO_SEC(52),
  DEPENDENCY_MINE_SEC(53),
  DEPENDENCY_DROPPABLE_GOLD_SEC(54),
  COOLDOWN_FIRST_AID_SEC(55),
  COOLDOWN_DOUBLE_ARMOR_SEC(56),
  COOLDOWN_DOUBLE_DAMAGE_SEC(57),
  COOLDOWN_NITRO_SEC(58),
  COOLDOWN_MINE_SEC(59),
  COOLDOWN_DROPPABLE_GOLD_SEC(60),
  DURATION_FIRST_AID_SEC(61),
  DURATION_DOUBLE_ARMOR_SEC(62),
  DURATION_DOUBLE_DAMAGE_SEC(63),
  DURATION_NITRO_SEC(64),
  ATTACK_EFFECT(65),
  FIRST_AID_EFFECT_INSTANT(66),
  FIRST_AID_EFFECT(67),
  PROTECTION_EFFECT(68),
  SPEED_EFFECT(69),
  SHOTGUN_IMPACT_FORCE(70),
  DISCHARGE_SPEED(71),
  FREEZE_PER_TICK(72),
  VERTICAL_ANGLES(73),
  DRONE_RELOAD(74),
  DRONE_REPAIR_HEALTH(75),
  DRONE_INVENTORY(76),
  DRONE_INVENTORY_ADD(77),
  DRONE_BONUS_ADD(78),
  DRONE_FIRST_AID_BONUS_ADD(79),
  DRONE_OVERDRIVE_BOOST(80),
  DRONE_DEFEND(81),
  DRONE_ARMOR_BOOST(82),
  DRONE_MINE(83),
  DRONE_ADDITIONAL_MINES(84),
  DRONE_MINES_ACTIVATION_DELAY(85),
  DRONE_MINES_PLACEMENT_RADIUS(86),
  DRONE_INVENTORY_COOLDOWN_BOOST(87),
  DRONE_POWER_BOOST(88),
  DRONE_POWER_DURATION(89),
  DRONE_CRITICAL_HEALTH(90),
  DRONE_REPAIR_RADIUS(91),
  DRONE_INVENTORY_RADIUS(92),
  DRONE_COOLDOWN_RADIUS(93),
  DRONE_CONSTANT_ARMOR_PERCENT(94),
  DRONE_CONSTANT_POWER_PERCENT(95),
  ULTIMATE_HEAL_HP(96),
  ULTIMATE_CHARGE_PER_SEC(97),
  ULTIMATE_CHARGE_PER_SCORE_POINT(98),
  ULTIMATE_SCORE_COOLDOWN_SEC(99),
  ULTIMATE_ACTIVATION_DISCHARGE_PER_SEC(100),
}
