= Narukami Server

This is not a full-fledged server, but a core with basic features to build upon.
Target feature level is a tournament server.

I discuss development of this server at link:https://discord.gg/RFXav6jRem[Vint Discord server],
a Tanki X server reimplementation community.

== Running

The server uses JVM system properties for configuration. You need to set:

* `res.root` to the `out` directory of the
link:https://github.com/NarukamiTO/resource-generator[resource generator].
* `res.url` to publicly accessible URL of the resources server (e.g., `http://127.0.1:5192` for local).
* `config.url` to publicly accessible URL of the config server (e.g., `http://127.0.0.1:5191` for local).
* `game.url` to publicly accessible endpoint of the game server (e.g., `127.0.0.1:5190` for local).

Prefix properties with `run.` to pass them to the server when running with `run` Gradle task.

Example:

[source,shell]
----
./gradlew run \
  -Drun.res.root=$(realpath ../resource-generator/out)
  -Drun.res.url=http://127.0.0.1:5192 \
  -Drun.config.url=http://127.0.0.1:5191 \
  -Drun.game.url=127.0.0.1:5190
----

You may configure log levels using `KOTLIN_LOG` environment variable with syntax
similar to `RUST_LOG`: `root_log_level,my.package=log_level`.

== Connecting

Standalone Flash Player / Ruffle::

* `http://127.0.0.1:5191/play.swf` which will automatically redirect URL similar to one below.
Parameters are passed as URL parts, i.e., `/play.swf/lang=ru/debug=true/autologin=username:password` because of bad client design.
* `http://127.0.0.1:5192/libs/AlternativaLoader.swf?config=127.0.0.1:5191/config.xml&resources=127.0.0.1:5192&balancer=http://127.0.0.1:5191/s/status.js&prefix=main.c&lang=ru&debug=true`

Optional query parameters:

* `lang` - client language, defaults to `en`.
* `debug` - whether to enable (useless?) debug mode, defaults to `false`.
* `autologin=username:password` - automatically log in with the given username and optional password.

== License

Licensed under GNU Affero General Public License, version 3.0 or later
(link:LICENSE[] or link:https://www.gnu.org/licenses/agpl-3.0.html[]).

**In short, you must make the entire source code available to your users if you host this server for anybody.**
**If you copy substantial part of the code, your project must also be licensed under AGPLv3.**
